kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  # If using another CNI (calico/flannel etc.) uncomment this to not install the kind provided default CNI 
  # disableDefaultCNI: true
  # Change the podSubnet if this conflicts with your local network or any VPN you maybe using
  # NOTE: If you change this you will need to update the metallb.yaml file.
  podSubnet: 192.168.168.0/24
nodes:
# Control plane nodes
- role: control-plane
  image: kindest/node:v1.19.3
  extraPortMappings:
  - containerPort: 30201
    hostPort: 30201
    listenAddress: "0.0.0.0"
- role: control-plane
  image: kindest/node:v1.19.3
  extraPortMappings:
  - containerPort: 30202
    hostPort: 30202
    listenAddress: "0.0.0.0"

# Worker nodes
- role: worker
  image: kindest/node:v1.19.3
- role: worker
  image: kindest/node:v1.19.3
- role: worker
  image: kindest/node:v1.19.3
